using HanieTo.Api.Domain;

namespace HanieTo.Api.ShopBot;

public enum T
{
    ChooseLanguage,
    LanguageName,
    WelcomeMenu,
    BrowseProducts,
    MyOrders,
    Help,
    LanguageButton,
    HelpText,
    Categories,
    PickProduct,
    ProductStock,
    ProductPrice,
    ChooseQuantity,
    BuyButton,
    Back,
    Home,
    NoProducts,
    OutOfStockShort,
    OrderPlaced,
    OrderId,
    OutOfStock,
    NoOrders,
    YourOrders,
    OrderTotal,
    ProductGone,
    ViewCart,
    AddToCart,
    AddedToCart,
    CartTitle,
    CartEmpty,
    Checkout,
    ClearCart,
    ContinueShopping,
    UseMenu,
    WelcomePrompt
}

// Trilingual strings for the shop bot (English / Russian / Persian). Telegram
// renders right-to-left automatically for Persian based on the text content, so
// no special direction handling is needed here.
public static class BotLocalization
{
    private static readonly Dictionary<BotLanguage, Dictionary<T, string>> Strings = new()
    {
        [BotLanguage.English] = new()
        {
            [T.ChooseLanguage] = "🌐 Please choose your language:",
            [T.LanguageName] = "🇬🇧 English",
            [T.WelcomeMenu] = "🏪 *Welcome to our shop!*\n\nWhat would you like to do?",
            [T.BrowseProducts] = "🛍 Browse Products",
            [T.MyOrders] = "📦 My Orders",
            [T.Help] = "ℹ️ Help",
            [T.LanguageButton] = "🌐 Language",
            [T.HelpText] = "ℹ️ *Help*\n\nBrowse products by category, check live stock, and place an order in a few taps. Your order is created as soon as you confirm.\n\nUse the buttons to navigate — you can always come back with the 🏠 Home button.",
            [T.Categories] = "🛍 *Categories*\n\nChoose a category:",
            [T.PickProduct] = "🗂 *{0}*\n\nChoose a product:",
            [T.ProductStock] = "In stock",
            [T.ProductPrice] = "Price",
            [T.ChooseQuantity] = "🔢 How many would you like?",
            [T.BuyButton] = "🛒 Buy",
            [T.Back] = "⬅️ Back",
            [T.Home] = "🏠 Home",
            [T.NoProducts] = "😔 No products are available right now.",
            [T.OutOfStockShort] = "out of stock",
            [T.OrderPlaced] = "✅ *Order placed!*\n\n{0}\n\n*{1}:* {2}\n{3}: `{4}`",
            [T.OrderId] = "Order ID",
            [T.OutOfStock] = "❌ Sorry, this item is out of stock.",
            [T.NoOrders] = "🗂 You haven't placed any orders yet.",
            [T.YourOrders] = "📦 *Your recent orders*",
            [T.OrderTotal] = "Total",
            [T.ProductGone] = "This product is no longer available.",
            [T.ViewCart] = "🛒 Cart",
            [T.AddToCart] = "➕ Add to cart",
            [T.AddedToCart] = "✅ Added to your cart.",
            [T.CartTitle] = "🛒 *Your cart*",
            [T.CartEmpty] = "🛒 Your cart is empty.",
            [T.Checkout] = "✅ Checkout",
            [T.ClearCart] = "🗑 Clear cart",
            [T.ContinueShopping] = "🛍 Continue shopping",
            [T.UseMenu] = "⚠️ Please use the menu below 👇",
            [T.WelcomePrompt] = "🏪 *Welcome to our shop!*\n\nUse the menu below 👇"
        },
        [BotLanguage.Russian] = new()
        {
            [T.ChooseLanguage] = "🌐 Пожалуйста, выберите язык:",
            [T.LanguageName] = "🇷🇺 Русский",
            [T.WelcomeMenu] = "🏪 *Добро пожаловать в наш магазин!*\n\nЧто вы хотите сделать?",
            [T.BrowseProducts] = "🛍 Товары",
            [T.MyOrders] = "📦 Мои заказы",
            [T.Help] = "ℹ️ Помощь",
            [T.LanguageButton] = "🌐 Язык",
            [T.HelpText] = "ℹ️ *Помощь*\n\nПросматривайте товары по категориям, проверяйте наличие и оформляйте заказ в несколько нажатий. Заказ создаётся сразу после подтверждения.\n\nИспользуйте кнопки для навигации — вернуться сюда можно кнопкой 🏠 Домой.",
            [T.Categories] = "🛍 *Категории*\n\nВыберите категорию:",
            [T.PickProduct] = "🗂 *{0}*\n\nВыберите товар:",
            [T.ProductStock] = "В наличии",
            [T.ProductPrice] = "Цена",
            [T.ChooseQuantity] = "🔢 Сколько штук вы хотите?",
            [T.BuyButton] = "🛒 Купить",
            [T.Back] = "⬅️ Назад",
            [T.Home] = "🏠 Домой",
            [T.NoProducts] = "😔 Сейчас нет доступных товаров.",
            [T.OutOfStockShort] = "нет в наличии",
            [T.OrderPlaced] = "✅ *Заказ оформлен!*\n\n{0}\n\n*{1}:* {2}\n{3}: `{4}`",
            [T.OrderId] = "Номер заказа",
            [T.OutOfStock] = "❌ К сожалению, товара нет в наличии.",
            [T.NoOrders] = "🗂 У вас пока нет заказов.",
            [T.YourOrders] = "📦 *Ваши последние заказы*",
            [T.OrderTotal] = "Итого",
            [T.ProductGone] = "Этот товар больше недоступен.",
            [T.ViewCart] = "🛒 Корзина",
            [T.AddToCart] = "➕ В корзину",
            [T.AddedToCart] = "✅ Добавлено в корзину.",
            [T.CartTitle] = "🛒 *Ваша корзина*",
            [T.CartEmpty] = "🛒 Ваша корзина пуста.",
            [T.Checkout] = "✅ Оформить",
            [T.ClearCart] = "🗑 Очистить",
            [T.ContinueShopping] = "🛍 Продолжить покупки",
            [T.UseMenu] = "⚠️ Пожалуйста, используйте меню ниже 👇",
            [T.WelcomePrompt] = "🏪 *Добро пожаловать в наш магазин!*\n\nИспользуйте меню ниже 👇"
        },
        [BotLanguage.Persian] = new()
        {
            [T.ChooseLanguage] = "🌐 لطفاً زبان خود را انتخاب کنید:",
            [T.LanguageName] = "🇮🇷 فارسی",
            [T.WelcomeMenu] = "🏪 *به فروشگاه ما خوش آمدید!*\n\nچه کاری می‌خواهید انجام دهید؟",
            [T.BrowseProducts] = "🛍 مشاهده محصولات",
            [T.MyOrders] = "📦 سفارش‌های من",
            [T.Help] = "ℹ️ راهنما",
            [T.LanguageButton] = "🌐 زبان",
            [T.HelpText] = "ℹ️ *راهنما*\n\nمحصولات را بر اساس دسته‌بندی ببینید، موجودی را بررسی کنید و با چند لمس سفارش دهید. سفارش شما بلافاصله پس از تأیید ثبت می‌شود.\n\nبرای جابجایی از دکمه‌ها استفاده کنید — همیشه می‌توانید با دکمه 🏠 خانه بازگردید.",
            [T.Categories] = "🛍 *دسته‌بندی‌ها*\n\nیک دسته را انتخاب کنید:",
            [T.PickProduct] = "🗂 *{0}*\n\nیک محصول را انتخاب کنید:",
            [T.ProductStock] = "موجودی",
            [T.ProductPrice] = "قیمت",
            [T.ChooseQuantity] = "🔢 چه تعداد می‌خواهید؟",
            [T.BuyButton] = "🛒 خرید",
            [T.Back] = "⬅️ بازگشت",
            [T.Home] = "🏠 خانه",
            [T.NoProducts] = "😔 در حال حاضر محصولی موجود نیست.",
            [T.OutOfStockShort] = "ناموجود",
            [T.OrderPlaced] = "✅ *سفارش ثبت شد!*\n\n{0}\n\n*{1}:* {2}\n{3}: `{4}`",
            [T.OrderId] = "شماره سفارش",
            [T.OutOfStock] = "❌ متأسفانه این محصول ناموجود است.",
            [T.NoOrders] = "🗂 شما هنوز سفارشی ثبت نکرده‌اید.",
            [T.YourOrders] = "📦 *سفارش‌های اخیر شما*",
            [T.OrderTotal] = "مجموع",
            [T.ProductGone] = "این محصول دیگر در دسترس نیست.",
            [T.ViewCart] = "🛒 سبد خرید",
            [T.AddToCart] = "➕ افزودن به سبد",
            [T.AddedToCart] = "✅ به سبد خرید شما اضافه شد.",
            [T.CartTitle] = "🛒 *سبد خرید شما*",
            [T.CartEmpty] = "🛒 سبد خرید شما خالی است.",
            [T.Checkout] = "✅ تسویه حساب",
            [T.ClearCart] = "🗑 خالی کردن سبد",
            [T.ContinueShopping] = "🛍 ادامه خرید",
            [T.UseMenu] = "⚠️ لطفاً از منوی زیر استفاده کنید 👇",
            [T.WelcomePrompt] = "🏪 *به فروشگاه ما خوش آمدید!*\n\nاز منوی زیر استفاده کنید 👇"
        }
    };

    public static string Get(BotLanguage language, T key) => Strings[language][key];

    public static string Get(BotLanguage language, T key, params object[] args) =>
        string.Format(Strings[language][key], args);
}
